version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wp-network

  wordpress:
    image: bitnami/wordpress-nginx:latest
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_NAME=wordpress1_db
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./php.ini:/opt/bitnami/php/etc/php.ini
    netowrks:
      - wp-network

  nginx:
    image: nginx:latest
    depends_on:
      - wordpress
    volumes:
      - ./domain.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - wp-network

networks:
  wp-network:
    name: wp-network
  